"""
constants.py

A collection of helpful constants for umich's knack.
"""



################################################################################
# Constants
################################################################################
MASTERS = {"MHSA","MLArch", "DNP" , "MUP", "MHI", "MSW", "MFA", "AMusD", "MBA",
           "MPH", "MAcc", "MPP", "MArch", "MSE", "MEng", "MSI", "MS", "MA"}


# Original (HR) Names
# ALL_DEPTS = {
#     "Aerospace Engineering",
#     "Bioinformatics",
#     "Biological Chemistry Dept",
#     "Biomedical Engineering",
#     "Biostatistics Department",
#     "Cell and Developmental Biology",
#     "Chemical Engineering Dept",
#     "Civil & Environmental Engr",
#     "COE Climate & Space",
#     "CoE Design Science Program",
#     "COE EECS - ECE Division",
#     "CoE Integrative Sys & Design",
#     "CoE Robotics Institute",
#     "CoE Undergraduate Education",
#     "Coll of Arch & Urban Planning",
#     "College of Pharmacy",
#     "Comp Med and Bioinformatics",
#     "Dbn Col of Eng-Computer & Info",
#     "Dbn Col of Eng-Electric & Comp",
#     "Dbn Col of Eng-Indust & Sys En",
#     "Dbn Coll of Eng-Mechanical Eng",
#     "EECS - CSE Division",
#     "Environmental Health Sciences",
#     "Epidemiology Department",
#     "Flint Biology",
#     "Flint Physical Therapy",
#     "Flint School of Management",
#     "G. Ford Sc Pub Pol",
#     "Graduate School Administration",
#     "Graduate studies",
#     "Health Management and Policy",
#     "Hlth Behavior & Hlth Ed Dept",
#     "Human Genetics Department",
#     "ICPSR - Summer Program",
#     "Industrial & Operations Engin",
#     "Library Collect - General",
#     "Library Learn&Teach-General",
#     "Library Learn&Teach-User Info",
#     "LSA American Culture",
#     "LSA Anthropology",
#     "LSA Asian Languages & Cultures",
#     "LSA Astronomy",
#     "LSA Biology - Undergraduate",
#     "LSA Biophysics",
#     "LSA Chemistry",
#     "LSA Classical Studies",
#     "LSA Communication Studies",
#     "LSA Comparative Literature",
#     "LSA DAAS",
#     "LSA Earth & Environmental Sci.",
#     "LSA Ecology & Evolutionary Bio",
#     "LSA Economics",
#     "LSA English Language & Lit.",
#     "LSA English Language Institute",
#     "LSA Germanic Languages & Lit.",
#     "LSA History",
#     "LSA History of Art",
#     "LSA II: Japanese Studies",
#     "LSA II: Prg Intl Comp Studies",
#     "LSA II: Russ, EE & Eurasian St",
#     "LSA Linguistics",
#     "LSA Linguistics: Weinberg ICS",
#     "LSA Mathematics",
#     "LSA Molec./Cell./Develop. Bio",
#     "LSA Near Eastern Studies",
#     "LSA Organizational Studies",
#     "LSA Philosophy",
#     "LSA Physics",
#     "LSA Political Science",
#     "LSA Political Science: MIW",
#     "LSA Psychology",
#     "LSA Romance Languages & Lit.",
#     "LSA Screen Arts & Cultures",
#     "LSA Slavic Languages & Lit.",
#     "LSA Sociology",
#     "LSA Statistics",
#     "LSA UG: Comprehensive Studies",
#     "LSA UG: Curriculum Support",
#     "LSA UG: Environment",
#     "LSA UG: Global Scholars Prog",
#     "LSA UG: Hlth. Science Scholars",
#     "LSA UG: Honors",
#     "LSA UG: InterGroup Relations",
#     "LSA UG: Residential College",
#     "LSA UG: WISE-RP",
#     "LSA Women's Studies",
#     "Materials Science & Engin.",
#     "Mechanical Engineering",
#     "Microbiology and Immunology",
#     "Molec & Integrative Physiology",
#     "Naval Arch & Marine Dept",
#     "Neuroscience Graduate Program",
#     "Nuclear Eng & Radiological Sci",
#     "Nutritional Sciences",
#     "Pharmacology Department",
#     "Rackham Communications",
#     "Rackham Grad Student Success",
#     "ROSS SCH Doctoral Programs",
#     "ROSS SCH MACC PRG",
#     "ROSS SCH Marketing",
#     "Sch of Public Hlth-Dean's Ofc",
#     "School of Education",
#     "School of Information",
#     "School of Kinesiology",
#     "School of Music,Theatre&Dance",
#     "School of Social Work",
#     "SEAS Office of Academic Prgms",
#     "SMTD Assoc Dean Grad Studies",
#     "SMTD Department of Dance",
#     "SMTD Michigan Marching Band",
#     "SOE - TFA",
#     "SOE- Teacher Education",
#     "SOE-CPEP",
#     "SOE-CSHPE",
#     "SOE-Educational Studies",
#     "SPHDO-Undergraduate Student Se",
#     "SRC-Survey Methodology",
#     "Stamps School of Art & Design",
#     "Urban Planning"
# }
ALL_DEPTS = {
    "COE - Aerospace",
    "COE - Biomedical",
    "COE - Chemical",
    "COE - Civil & Environmental",
    "COE - Climate & Space",
    "COE - Computer Science (CS)",
    "COE - Design Science Program",
    "COE - Electrical & Computer Engineering (ECE)",
    "COE - Industrial & Operations (IOE)",
    "COE - Integrative Systems & Design",
    "COE - Materials Science",
    "COE - Mechanical",
    "COE - Naval Architecture & Marine",
    "COE - Nuclear Engineering & Radiological Sciences (NERS)",
    "COE - Robotics Institute",
    "COE - Undergraduate Education",
    "College of Pharmacy",
    "Ford School - Public Policy",
    "Graduate School Administration",
    "ICPSR - Summer Program",
    "Institute for Social Research - SRC: Survey Methodology",
    "Library - Collections",
    "Library - Learning & Teaching (General)",
    "Library - Learning & Teaching (User Info)",
    "LSA - American Culture",
    "LSA - Anthropology",
    "LSA - Asian Languages & Cultures",
    "LSA - Astronomy",
    "LSA - Biophysics",
    "LSA - Chemistry",
    "LSA - Classics",
    "LSA - Communications",
    "LSA - Comparative Literature",
    "LSA - DAAS",
    "LSA - Earth & Environmental Sciences",
    "LSA - Ecology & Evolutionary Biology",
    "LSA - Economics",
    "LSA - English Language & Literature",
    "LSA - Germanic Languages & Literature",
    "LSA - History",
    "LSA - History of Art",
    "LSA - II: Program in International & Comparative Studies (PICS)",
    "LSA - II: Russian, East European, & Eurasian Studies",
    "LSA - Linguistics",
    "LSA - Mathematics",
    "LSA - Molecular, Cellular, and Developmental Biology",
    "LSA - Near Eastern Studies",
    "LSA - Organizational Studies",
    "LSA - Philosophy",
    "LSA - Physics",
    "LSA - Political Science",
    "LSA - Political Science: Michigan in Washington",
    "LSA - Psychology",
    "LSA - Romance Languages & Literatures",
    "LSA - Screen Arts & Cultures",
    "LSA - Slavic Languages & Literature",
    "LSA - Sociology",
    "LSA - Statistics",
    "LSA - UG Comprehensive Studies Program",
    "LSA - UG Curriculum Support",
    "LSA - UG English Language Institute",
    "LSA - UG Health Science Scholars Program",
    "LSA - UG Health Science Scholars ProgramLSA - UG Global Scholars Program",
    "LSA - UG Honors Program",
    "LSA - UG Intergroup Relations",
    "LSA - UG Program in Biology",
    "LSA - UG Program in the Environment",
    "LSA - UG Residential College",
    "LSA - UG Women in Science & Engineering Residence Program",
    "LSA - Weinberg Institute for Cognitive Science",
    "LSA - Women's Studies",
    "LSA II: Japanese Studies",
    "Medicine - Bioinformatics*",
    "Medicine - Biological Chemistry",
    "Medicine - Cell and Developmental Biology",
    "Medicine - Computational Medicine & Bioinformatics",
    "Medicine - Human Genetics*",
    "Medicine - Microbiology & Immunology*",
    "Medicine - Molecular & Integrative Physiology*",
    "Medicine - Neuroscience",
    "Medicine - Pharmacology",
    "Rackham - Communications*",
    "Rackham - Graduate Student Success*",
    "Ross School of Business - MAcc",
    "Ross School of Business - Marketing",
    "Ross School of Business - PhD",
    "School of Education",
    "School of Education - CPEP*",
    "School of Education - CSHPE*",
    "School of Education - Educational Studies",
    "School of Education - Teacher Education",
    "School of Education - TFA",
    "School of Information",
    "School of Kinesiology",
    "School of Social Work",
    "SEAS Office of Academic Prgms",
    "SMTD",
    "SMTD - Dance",
    "SMTD - Dance*",
    "SMTD - Graduate Studies",
    "SMTD - Marching Band",
    "SPH - Biostatistics",
    "SPH - Dean's Office",
    "SPH - Environmental Health Sciences",
    "SPH - Epidemiology",
    "SPH - Health Behavior & Health Education",
    "SPH - Health Management & Policy",
    "SPH - Nutritional Sciences",
    "SPH - Student Services (UG)",
    "Stamps - Art & Design",
    "Taubman - Architecture",
    "Taubman - Urban Planning",
    "DBN COE - Computer & Info",
    "DBN COE - Electrical & Computer Science",
    "DBN COE - Industrial & Systems",
    "DBN COE - Mechanical",
    "Flint - Biology",
    "Flint - Physical Therapy",
    "Flint - School of Management"
}


NORTH_CAMPUS_DEPTS = {
    "COE - Aerospace",
    "COE - Biomedical",
    "COE - Chemical",
    "COE - Civil & Environmental",
    "COE - Climate & Space",
    "COE - Computer Science (CS)",
    "COE - Design Science Program",
    "COE - Electrical & Computer Engineering (ECE)",
    "COE - Industrial & Operations (IOE)",
    "COE - Integrative Systems & Design",
    "COE - Materials Science",
    "COE - Mechanical",
    "COE - Naval Architecture & Marine",
    "COE - Nuclear Engineering & Radiological Sciences (NERS)",
    "COE - Robotics Institute",
    "COE - Undergraduate Education",
    "SMTD",
    "SMTD - Dance",
    "SMTD - Dance*",
    "SMTD - Graduate Studies",
    "SMTD - Marching Band",
    "Stamps - Art & Design",
    "Taubman - Architecture",
    "Taubman - Urban Planning",
}

ENGINEERING_DEPTS = {
    "COE - Aerospace",
    "COE - Biomedical",
    "COE - Chemical",
    "COE - Civil & Environmental",
    "COE - Climate & Space",
    "COE - Computer Science (CS)",
    "COE - Design Science Program",
    "COE - Electrical & Computer Engineering (ECE)",
    "COE - Industrial & Operations (IOE)",
    "COE - Integrative Systems & Design",
    "COE - Materials Science",
    "COE - Mechanical",
    "COE - Naval Architecture & Marine",
    "COE - Nuclear Engineering & Radiological Sciences (NERS)",
    "COE - Robotics Institute",
    "COE - Undergraduate Education"
}


# A "Dept. Code" is the shortened code attached to class names
# Ex. for the course EECS 320, "EECS" is the Dept Code
#
# NOTE: Some of these I'm guessing at and will probably have to change!
# ALSO: *** NEED TO UPDATE THESE WITH NEW DEPT NAMES ***
DEPT_TO_DEPTCODES = {
    "COE - Aerospace": ["AEROSP"],
    "COE - Biomedical": ["BIOMEDE"],
    "COE - Chemical": ["CHE"],
    "COE - Civil & Environmental": ["CEE"],
    "COE - Climate & Space": ["CLIMATE", "SPACE", "AOSS"],
    "COE - Computer Science (CS)": ["EECS"],
    "COE - Design Science Program": ["DESCI"],
    "COE - Electrical & Computer Engineering (ECE)": ["EECS"],
    "COE - Industrial & Operations (IOE)": ["IOE"],
    "COE - Integrative Systems & Design": ["ISD"],
    "COE - Materials Science": ["MATSCIE"],
    "COE - Mechanical": ["MECHENG"],
    "COE - Naval Architecture & Marine": ["NAVARCH"],
    "COE - Nuclear Engineering & Radiological Sciences (NERS)": ["NERS"],
    "COE - Robotics Institute": ["RAV"],
    "COE - Undergraduate Education": ["ENGR"],
    "College of Pharmacy": ["PHARMACY"],
    "Ford School - Public Policy": ["PUBPOL"],
    "Graduate School Administration": ["RACKHAM"],
    "ICPSR - Summer Program": [""],
    "Institute for Social Research - SRC: Survey Methodology": [""],
    "Library - Collections": [""],
    "Library - Learning & Teaching (General)": [""],
    "Library - Learning & Teaching (User Info)": [""],
    "LSA - American Culture": ["AMCULT"],
    "LSA - Anthropology": ["ANTHRBIO","ANTHRCULT"],
    "LSA - Asian Languages & Cultures": ["ASIANLAN"],
    "LSA - Astronomy": ["ASTRO"],
    "LSA - Biophysics": ["BIOPHYS"],
    "LSA - Chemistry": ["CHEM"],
    "LSA - Classics": [""],
    "LSA - Communications": ["COMM"],
    "LSA - Comparative Literature": ["COMPLIT"],
    "LSA - DAAS": [""],
    "LSA - Earth & Environmental Sciences": ["EARTH"],
    "LSA - Ecology & Evolutionary Biology": ["EEB"],
    "LSA - Economics": ["ECON"],
    "LSA - English Language & Literature": ["ENGLISH"],
    "LSA - Germanic Languages & Literature": ["GERMAN"],
    "LSA - History": ["HISTORY"],
    "LSA - History of Art": ["HISTART"],
    "LSA - II: Program in International & Comparative Studies (PICS)": [""],
    "LSA - II: Russian, East European, & Eurasian Studies": [""],
    "LSA - Linguistics": ["LING"],
    "LSA - Mathematics": ["MATH"],
    "LSA - Molecular, Cellular, and Developmental Biology": ["MCDB"],
    "LSA - Museum of Anthropological Archaeology": [""],
    "LSA - Near Eastern Studies": ["NEAREAST"],
    "LSA - Organizational Studies": ["ORGSTUDY"],
    "LSA - Philosophy": ["PHIL"],
    "LSA - Physics": ["PHYSICS"],
    "LSA - Political Science": ["POLSCI"],
    "LSA - Political Science: Michigan in Washington": ["POLSCI"],
    "LSA - Program in the Environment": ["ENVIRON"],
    "LSA - Psychology": ["PSYCH"],
    "LSA - Romance Languages & Literatures": ["ROMLANG", "FRENCH"],
    "LSA - Screen Arts & Cultures": ["SAC"],
    "LSA - Slavic Languages & Literature": ["SLAVIC"],
    "LSA - Sociology": ["SOC"],
    "LSA - Statistics": ["STATS"],
    "LSA - UG Comprehensive Studies Program": ["CSP"],
    "LSA - UG Curriculum Support": [""],
    "LSA - UG English Language Institute": ["ELI"],
    "LSA - UG Health Science Scholars Program": [""],
    "LSA - UG Health Science Scholars ProgramLSA - UG Global Scholars Program": [""],
    "LSA - UG Honors Program": [""],
    "LSA - UG Intergroup Relations": [""],
    "LSA - UG Program in Biology": ["BIOLOGY"],
    "LSA - UG Program in the Environment": ["ENVIRON"],
    "LSA - UG Residential College": ["RCARTS","RCCORE","RCHUMS","RCIDIV",
                                    "RCLANG","RCNSCI","RCSSCI"],
    "LSA - UG Women in Science & Engineering Residence Program": [""],
    "LSA - Weinberg Institute for Cognitive Science": ["LING"],
    "LSA - Women's Studies": ["WOMENSTD"],
    "LSA II: Japanese Studies": ["CJS"],
    "Medicine - Bioinformatics*": ["BIOINF"],
    "Medicine - Biological Chemistry": ["BIOLCHEM"],
    "Medicine - Cell and Developmental Biology": ["CDB"],
    "Medicine - Computational Medicine & Bioinformatics": ["BIOINF"],
    "Medicine - Human Genetics*": ["HUMGEN"],
    "Medicine - Learning Health Sciences": [""],
    "Medicine - Microbiology & Immunology*": ["BIOLOGY"],
    "Medicine - Molecular & Integrative Physiology*": [""],
    "Medicine - Neuroscience": ["NEUROSCI"],
    "Medicine - Office of Graduate and Postdoctoral Studies": [""],
    "Medicine - Pharmacology": ["PHARMACY"],
    "Pharmacy - Medicinal Chemistry": ["PHARMACY"],
    "Pharmacy - Pharmaceutical Science": ["PHARMACY"],
    "Rackham - Communications*": [""],
    "Rackham - Graduate Student Success*": [""],
    "Ross School of Business - MAcc": [""],
    "Ross School of Business - Marketing": [""],
    "Ross School of Business - PhD": [""],
    "School for Environment and Sustainability": ["EAS"],
    "School of Education": ["EDUC"],
    "School of Education - Academic Affairs": ["EDUC"],
    "School of Education - CPEP*": ["EDUC"],
    "School of Education - CSHPE*": ["EDUC"],
    "School of Education - Educational Studies": ["EDUC"],
    "School of Education - JPEE": ["EDUC"],
    "School of Education - Teacher Education": ["EDUC"],
    "School of Education - TFA": ["EDUC"],
    "School of Information": ["SI"],
    "School of Kinesiology": ["AT","HF","KINESLGY","MOVESCI","SM"],
    "School of Social Work": ["SW"],
    "SEAS Office of Academic Prgms": [""],
    "SMTD": [ "DANCE","ARTSADMIN","BARCELLO",
              "BASSOON","CARILLON","CELLO",
              "CLARINET","COMP","CONDUCT",
              "DBLBASS","EARLYMUS","ENS",
              "EUPHBARI","FLUTE","FPIANO",
              "FRENHORN","GUITAR","HARP",
              "JAZZ","MUSED","MUSICOL",
              "MUSPERF","MUSTHTRE","OBOE",
              "OPERA","ORGAN","ORGANLIT",
              "PAT","PERCUSS","PIANO",
              "PIANOLP","SACREDMU","SAX",
              "STDEXCH","THEORY","TROMBONE",
              "TRUM","TUBA","VIOLA","VIOLIN",
              "VOICE","VOICELIT","THTREMUS" ],
    "SMTD - Dance": ["DANCE"],
    "SMTD - Dance*": ["DANCE"],
    "SMTD - Graduate Studies": [""],
    "SMTD - Marching Band": [""],
    "SPH - Biostatistics": ["BIOSTAT"],
    "SPH - Dean's Office": [""],
    "SPH - Environmental Health Sciences": ["EHS"],
    "SPH - Epidemiology": ["EPID"],
    "SPH - Health Behavior & Health Education": ["HBEHED"],
    "SPH - Health Management & Policy": ["HMP"],
    "SPH - Nutritional Sciences": ["NUTR"],
    "SPH - Student Services (UG)": [""],
    "Stamps - Art & Design": ["ARTDES"],
    "Taubman - Architecture": ["ARCH"],
    "Taubman - Architecture and Urban Planning Admin": ["ARCH"],
    "Taubman - Urban Planning": ["URP"],
    "DBN COE - Computer & Info": [""],
    "DBN COE - Electrical & Computer Science": [""],
    "DBN COE - Industrial & Systems": [""],
    "DBN COE - Mechanical": [""],
    "Flint - Biology": [""],
    "Flint - Physical Therapy": [""],
    "Flint - School of Management": [""],
    ## Catches people w/o assigned departments
    ## (sometimes happens early in term)
    "": [""]
}
